import StaffCode from '../models/StaffCode.js';

const staffCodeController = {
  // Generate new staff code (Admin only)
  generateStaffCode: async (req, res) => {
    try {
      const adminId = req.user.id; // From auth middleware

      const newStaffCode = await StaffCode.createStaffCode(adminId);

      res.status(201).json({
        success: true,
        message: 'Staff code generated successfully',
        data: {
          staff_code: newStaffCode.staff_code,
          created_at: newStaffCode.created_at,
          is_used: newStaffCode.is_used
        }
      });
    } catch (error) {
      console.error('Generate staff code error:', error);
      res.status(500).json({
        success: false,
        message: 'Failed to generate staff code',
        error: error.message
      });
    }
  },

  // Get all staff codes (Admin only)
  getAllStaffCodes: async (req, res) => {
    try {
      const staffCodes = await StaffCode.getAllStaffCodes();

      res.status(200).json({
        success: true,
        message: 'Staff codes retrieved successfully',
        data: staffCodes,
        count: staffCodes.length
      });
    } catch (error) {
      console.error('Get staff codes error:', error);
      res.status(500).json({
        success: false,
        message: 'Failed to retrieve staff codes',
        error: error.message
      });
    }
  },

  // Get staff codes generated by current admin
  getMyStaffCodes: async (req, res) => {
    try {
      const adminId = req.user.id;

      const staffCodes = await StaffCode.getStaffCodesByCreator(adminId);

      res.status(200).json({
        success: true,
        message: 'Your staff codes retrieved successfully',
        data: staffCodes,
        count: staffCodes.length
      });
    } catch (error) {
      console.error('Get my staff codes error:', error);
      res.status(500).json({
        success: false,
        message: 'Failed to retrieve your staff codes',
        error: error.message
      });
    }
  },

  // Generate multiple staff codes at once
  generateMultipleStaffCodes: async (req, res) => {
    try {
      const adminId = req.user.id;
      const { count = 1 } = req.body;

      if (count < 1 || count > 10) {
        return res.status(400).json({
          success: false,
          message: 'Count must be between 1 and 10'
        });
      }

      const generatedCodes = [];
      for (let i = 0; i < count; i++) {
        const newCode = await StaffCode.createStaffCode(adminId);
        generatedCodes.push({
          staff_code: newCode.staff_code,
          created_at: newCode.created_at,
          is_used: newCode.is_used
        });
      }

      res.status(201).json({
        success: true,
        message: `${count} staff code(s) generated successfully`,
        data: generatedCodes,
        count: generatedCodes.length
      });
    } catch (error) {
      console.error('Generate multiple staff codes error:', error);
      res.status(500).json({
        success: false,
        message: 'Failed to generate staff codes',
        error: error.message
      });
    }
  }
};

export default staffCodeController;