import express from 'express';
const router = express.Router();
import staffCodeController from '../controller/staffCodeController.js';
import  authenticateToken  from '../middleware/authMiddleware.js';
import { requireAdmin } from '../middleware/roleMiddleware.js';

// All routes require authentication and admin role
router.use(authenticateToken);
router.use(requireAdmin);

// Generate a single staff code
router.post('/generate', staffCodeController.generateStaffCode);

// Generate multiple staff codes
router.post('/generate-multiple', staffCodeController.generateMultipleStaffCodes);

// Get all staff codes (all admins)
router.get('/all', staffCodeController.getAllStaffCodes);

// Get staff codes generated by current admin
router.get('/my-codes', staffCodeController.getMyStaffCodes);

export default router;